### ISSUE TITLE
Maven Central publishing - snapshots, releases etc

### ISSUE THREAD

**Issue by nealeu** [bennidi/mbassador-spring#7]
Hi,

We'd like to use mbassador-spring in a project, but it's currently a pain to use in builds due to not having published Maven artifacts.

Would you accept a pull request to update pom.xml to do releases to Maven Central using mvn:release-prepare, mvn:release-perform?

There are also good instructions at http://central.sonatype.org/pages/ossrh-guide.html with a Parent POM available to make life easy.

Thanks,

Neale

**Comment by bennidi** [comment]
Agree. PR is welcome. Thank you!

**Comment by nealeu** [comment]
Ok.  We'll see what time we can make to get it done. Unlikely to be this week...
